"""Generate agent-profile.md from studio submissions."""

from datetime import datetime, timezone

from backend.services.cursor_llm import complete as cursor_complete
from backend.services.cursor_llm import is_configured as cursor_configured
from backend.services.studio_tasks import resolve_studio_for_field


def _format_responses(responses: list) -> str:
    lines = []
    for r in responses:
        lines.append(f"### Task: {r.get('task_id', 'unknown')} ({r.get('task_type', '')})")
        data = r.get("response_data", {})
        for key, value in data.items():
            lines.append(f"- **{key}**: {value}")
        lines.append("")
    return "\n".join(lines)


def _not_assessed() -> str:
    return "_Not yet assessed — complete more Studio tasks to train this area._"


def _rule_based_profile(
    profile: dict,
    responses: list,
    studio_template: dict,
    tasks_completed: int = 0,
    total_tasks: int = 0,
) -> str:
    name = profile.get("full_name") or "Analyst"
    field = profile.get("field") or "Data Analysis"
    job = profile.get("current_job") or "Data Analyst"
    skillset = profile.get("skillset") or ""
    industry = profile.get("industry") or "—"

    investigation = next((r for r in responses if r.get("task_id") == "investigation_scenario"), None)
    sql_task = next((r for r in responses if r.get("task_id") == "sql_challenge"), None)
    interpret = next((r for r in responses if r.get("task_id") == "interpret_results"), None)
    comm = next((r for r in responses if r.get("task_id") == "stakeholder_communication"), None)
    method = next((r for r in responses if r.get("task_id") == "methodology_choice"), None)

    inv_data = (investigation or {}).get("response_data", {})
    sql_data = (sql_task or {}).get("response_data", {})
    int_data = (interpret or {}).get("response_data", {})
    comm_data = (comm or {}).get("response_data", {})
    meth_data = (method or {}).get("response_data", {})

    training_note = ""
    if total_tasks and tasks_completed < total_tasks:
        training_note = f"\n> Training progress: {tasks_completed}/{total_tasks} Studio tasks completed\n"

    return f"""# Agent Profile: {name}

> Generated by Minion AI Studio on {datetime.now(timezone.utc).strftime("%Y-%m-%d")}
> Studio: {studio_template.get("name", "Data Analyst Studio")}{training_note}

## Identity

| Attribute | Value |
|-----------|-------|
| Field | {field} |
| Current role | {job} |
| Industry | {industry} |
| Core skills | {skillset} |

## How This Person Thinks

### Investigation style
When faced with ambiguous metrics changes, this analyst prioritizes:

{inv_data.get("steps") or (_not_assessed() if not investigation else "—")}

**Reasoning pattern:** {inv_data.get("reasoning") or (_not_assessed() if not investigation else "Not captured")}

### SQL & technical approach
```sql
{sql_data.get("sql") or ("-- " + _not_assessed() if not sql_task else "-- No query submitted")}
```

**Edge-case awareness:** {sql_data.get("approach_notes") or (_not_assessed() if not sql_task else "—")}

### Interpretation & recommendations
- **Takeaway style:** {int_data.get("takeaway", "—")}
- **Action orientation:** {int_data.get("recommendation", "—")}
- **Confidence calibration:** {int_data.get("confidence", "—")}

### Communication style
- **Report structure:** {comm_data.get("structure", "—")}
- **Issue flagging:** {comm_data.get("issue_flagging", "—")}
- **Tone:** {comm_data.get("tone", "—")}

### Methodology preferences
- **Default method:** {meth_data.get("method", "—")}
- **Rationale:** {meth_data.get("rationale", "—")}
- **Data requirements:** {meth_data.get("data_needed", "—")}

## Agent Instructions (use as system context)

You are simulating **{name}**, a {job} with expertise in {field}.

1. **Investigate before concluding** — follow their step order when diagnosing metric changes.
2. **Write SQL** matching their style and assumptions noted above.
3. **Interpret data** with their confidence level and recommendation patterns.
4. **Communicate** using their preferred structure and tone.
5. **Choose methods** aligned with their stated methodology preferences.

When uncertain, ask clarifying questions the way a senior {field} professional would — direct, data-grounded, and action-oriented.
"""


def _ai_enhanced_profile(profile: dict, responses: list, studio_template: dict) -> str:
    try:
        prompt = f"""You are building a professional agent profile from a studio assessment.

User background:
- Name: {profile.get("full_name")}
- Field: {profile.get("field")}
- Job: {profile.get("current_job")}
- Skills: {profile.get("skillset")}
- Industry: {profile.get("industry")}

Studio responses:
{_format_responses(responses)}

Write a detailed agent-profile.md that captures HOW this person thinks and works — not just what they answered.
Include: Identity, Investigation Style, SQL Approach, Interpretation Patterns, Communication Style,
Methodology Preferences, and Agent Instructions (system prompt section).

Use markdown. Be specific and actionable so another AI can simulate this person's work style."""
        system = "You write professional agent profile documents in markdown."
        text = cursor_complete(system, prompt, max_wait_s=240)
        if text:
            return text
    except Exception:
        pass
    return _rule_based_profile(profile, responses, studio_template)


def generate_agent_profile(
    profile: dict,
    responses: list,
    field: str,
    tasks_completed: int = 0,
    total_tasks: int = 0,
) -> str:
    studio = resolve_studio_for_field(field)
    if cursor_configured():
        return _ai_enhanced_profile(profile, responses, studio)
    return _rule_based_profile(
        profile, responses, studio,
        tasks_completed=tasks_completed, total_tasks=total_tasks,
    )
